name: dio_extension
description: .
version: 2.1.0
homepage: https://github.com/hsul4n/dart-extensions/packages/dio

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.4

dev_dependencies:
  test: ^1.5.1
